language: android

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

notifications:
  email:
    - jacob@jacobmason.net
    - mdttrump97@bellsouth.net
